source 'https://rubygems.org'

gem 'rails', ENV['RAILS_VERSION']

gem 'coffee-rails', '~> 4.2.1'
gem 'jbuilder', '~> 2.5'
gem 'sass-rails', '~> 5.0.0'
gem 'uglifier', '~> 2.7.2'
gem 'haml-rails', '~> 0.9.0'

gem 'high_voltage', '~> 3.0'
gem 'meta-tags', require: 'meta_tags'

gem 'mysql2', '~> 0.3.20'
gem 'sqlite3'
gem 'unicorn', '~> 5.0.1'

group :development, :test do
  gem 'timecop'
  gem 'annotate', '~> 2.7.1'
  gem 'simplecov', require: false
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails', '~> 3.5.1'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :production, :ci do
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
