source 'https://rubygems.org'

gem 'rails', '4.2.5'

gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'high_voltage', '~> 2.2.1'
gem 'meta-tags', require: 'meta_tags'

gem 'mysql2', '~> 0.3.20'
gem 'sqlite3'
gem 'unicorn'

group :development, :test do
  gem 'letter_opener'
  gem 'timecop'
  gem 'annotate', '~> 2.6.5'
  gem 'simplecov', require: false
  gem 'factory_girl_rails', '~> 4.2'
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails', '~> 3.4'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :production, :ci do
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
